name: Pull Request

on:
  pull_request:
    branches:
      - master
      - development

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          yarn install
      - name: Run Coverage
        run: |
          yarn coverage