name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  pull-request:
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          yarn install
      - name: Run Coverage
        run: |
          yarn coverage